version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # You will paste your MongoDB Atlas URL here
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT=5000
      - NODE_ENV=env
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # The left side (3000) is the port you'll use in your browser. 
      # The right side (80) is the port Nginx is listening on inside the container.
      - "3000:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  consumer:
    build:
      context: ./backend/consumer
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M